### ISSUE TITLE
Lots of warnings in CLI

### ISSUE THREAD

**Issue by st-a** [stylus/stylus#2533]
hey there,
I am getting lots of warnings when invoking Stylus from the command line. Doesn't matter which option I use, e.g. `$ stylus --help`. Despite these warnings, Stylus is working as expected.

- Stylus 0.54.7
- Node.js 14.0.0
- Arch Linux

```
(node:113126) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:113126) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:113126) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:113126) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:113126) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:113126) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

<details>
<summary>$ node --trace-warnings index.js</summary>

```
(node:113140) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Boolean.Node [as constructor] (/usr/lib/node_modules/stylus/lib/nodes/node.js:44:23)
    at new Boolean (/usr/lib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/usr/lib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
(node:113140) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Boolean.Node [as constructor] (/usr/lib/node_modules/stylus/lib/nodes/node.js:45:23)
    at new Boolean (/usr/lib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/usr/lib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
(node:113140) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Boolean.Node [as constructor] (/usr/lib/node_modules/stylus/lib/nodes/node.js:46:25)
    at new Boolean (/usr/lib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/usr/lib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
(node:113140) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Boolean.Node [as constructor] (/usr/lib/node_modules/stylus/lib/nodes/node.js:44:23)
    at new Boolean (/usr/lib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/usr/lib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
(node:113140) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Boolean.Node [as constructor] (/usr/lib/node_modules/stylus/lib/nodes/node.js:45:23)
    at new Boolean (/usr/lib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/usr/lib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
(node:113140) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Boolean.Node [as constructor] (/usr/lib/node_modules/stylus/lib/nodes/node.js:46:25)
    at new Boolean (/usr/lib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/usr/lib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
```
</details>

**Comment by AdrianoCahete** [comment]
Same. That bug looks like to come from `ShellJS` shelljs/shelljs#973 in conjunction with node v14 nodejs/node#29935 .
Update the `shelljs` dependency to `0.8.4` seems to fix it, but isn't the stylus problem but one of this dependencies.

**Comment by buckle2000** [comment]
What even is the issue?

**Comment by st-a** [comment]
Those warnings are gone with stylus 0.54.8. The issue was fixed by #2538.

**Comment by zaneclaes** [comment]
@st-a I'm on `0.54.8` and still having these exact issues.

I do see the changes in the PR, though:

`cat node_modules/stylus/lib/nodes/index.js`
Yields:
```
/*!
 * Stylus - nodes
 * Copyright (c) Automattic <developer.wordpress.com>
 * MIT Licensed
 */

exports.lineno = null;
exports.column = null;
exports.filename = null;
[...]
```

**Comment by st-a** [comment]
hey @zaneclaes, I just checked with Node `v15.2.1` and Stylus `0.54.8` and did not see any issues. Could it be, you have Stylus installed locally and globally and one of them is not updated? Take a look at the output of `npm list --depth=0` vs. `npm list -g --depth=0` for example.

**Comment by zaneclaes** [comment]
FWIW, I'm on Node v14 and using yarn workspaces.

```
yarn list --depth=0 | grep stylus
├─ stylus-loader@4.3.0
├─ stylus@0.54.8
```

```
yarn list -g --depth=0 | grep stylus
├─ stylus-loader@4.3.0
├─ stylus@0.54.8
```

Same results from the package root vs. workspace root. This is the only project in the workspace with `stylus` installed. Moreover, I only just installed stylus for the first time (have never used it before a couple days ago), so I highly doubt there are lingering old versions on my system.

**Comment by zaneclaes** [comment]
As I look deeper at the stack trace, it seems that the `stylus` in question is loaded by `nib`. It seems the `nib` package was last published 4 years ago. I'm actually porting some code, so I'm a bit beyond my normal experience here. But the Webpack docs still seem to use `nib`. Is there something I'm missing re: getting the dependencies to line up?

```
(node:13462) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Boolean.Node [as constructor] (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/node.js:42:23)
    at new Boolean (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
(node:13462) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Boolean.Node [as constructor] (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/node.js:43:23)
    at new Boolean (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
(node:13462) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Boolean.Node [as constructor] (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/node.js:44:25)
    at new Boolean (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
(node:13462) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Boolean.Node [as constructor] (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/node.js:42:23)
    at new Boolean (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
(node:13462) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Boolean.Node [as constructor] (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/node.js:43:23)
    at new Boolean (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
(node:13462) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Boolean.Node [as constructor] (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/node.js:44:25)
    at new Boolean (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/Users/zaneclaes/OWS/node_modules/nib/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
```

**Comment by st-a** [comment]
There is an open Issue at `nib` regarding the outdated `stylus` dependency. It looks like you can override the dependency resolution manually with `yarn`: https://github.com/stylus/nib/issues/347#issuecomment-662947214
